name: Android CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: 'node_modules'
          key: 'yarn.lock'
  build:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.11
        with:
          path: 'node_modules'
          key: 'yarn.lock'
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
      - name: Build with Gradle
        run: cd android && ./gradlew build
