name: Android CI

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Format project
        run: yarn format:check
      - name: Lint project
        run: yarn lint
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: 'node_modules'
          key: 'yarn.lock'

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3.0.11
        with:
          path: 'node_modules'
          key: 'yarn.lock'
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
