name: Android CI

on:
  push:
    branches: ['development', 'master']
  pull_request:
    branches: ['development']

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Check project format
        run: yarn format:check
      - name: Lint project
        run: yarn lint
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
